# Generated by Django 4.2.13 on 2024-05-14 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('sign_up_method', models.CharField(default='Google', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MapEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('latGroup', models.IntegerField(blank=True, null=True)),
                ('lonGroup', models.IntegerField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('is_viewable', models.BooleanField(default=False)),
                ('tags', models.ManyToManyField(blank=True, related_name='map_entities', to='datamap.tag')),
                ('user_created', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datamap.user')),
            ],
        ),
        migrations.CreateModel(
            name='EntityAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='datamap.mapentity')),
            ],
        ),
        migrations.AddIndex(
            model_name='mapentity',
            index=models.Index(fields=['latGroup', 'lonGroup'], name='datamap_map_latGrou_901893_idx'),
        ),
    ]
